### ISSUE TITLE
Унифицировать язык

### ISSUE THREAD

**Issue by DarkHobbit** [DarkHobbit/chronoline#10]
Все надписи в программе привести к английскому языку и сделать русский перевод

**Comment by DarkHobbit** [comment]
Язык унифицирован, .ts сделан, ну а модифицировать и подключать его, думаю, буду в прикладных проектах. :) (Если это сделать в демке, потребуется городить механизм выбора языка и прочее...)

**Comment by RandomAmbersky** [comment]
;)

![1366386594332](https://cloud.githubusercontent.com/assets/436951/12480326/aaa11568-c052-11e5-97d3-ba60060d9dca.jpg)

**Comment by DarkHobbit** [comment]
Эээ... а здесь-то в чём троллейбус из буханки?

**Comment by RandomAmbersky** [comment]
"но зачем?" ;)

**Comment by DarkHobbit** [comment]
Что зачем, не хардкодить? Так это, вроде, не здесь обсуждалось... :<
