### ISSUE TITLE
Два января на линии

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#15]
при отображении в демке периода 01.01.2015 - 31.12.2015 появляется...
![2015-11-25 10 27 59](https://cloud.githubusercontent.com/assets/436951/11411718/03fd1a80-93e4-11e5-847a-3fc0baefbbca.png)

**Comment by DarkHobbit** [comment]
Да, проверил, есть такое. Вообще, подобный эффект когда-то был, но я его считал давным-давно вылеченным, после того, как переделал алгоритм пересчёта дат в координаты. Будем разбираться.

**Comment by DarkHobbit** [comment]
Вылечено - commit 4dada962b831cc0e9e82f87da707b25b9aad242a

**Comment by RandomAmbersky** [comment]
![2016-01-07 21 54 37](https://cloud.githubusercontent.com/assets/436951/12179702/6275d81a-b589-11e5-8418-0b673ae960dd.png)

Демка последней версии

**Comment by DarkHobbit** [comment]
Вроде бы победил... надо будет ещё погонять

**Comment by DarkHobbit** [comment]
Мне кажется, этой баги больше нет?..

**Comment by RandomAmbersky** [comment]
да, вроде как )
