### ISSUE TITLE
1 марта наступает раньше

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#16]
при отображении периода с 01/01/2015-01/31/2015  двигал флажок... 1 марта раньше отображаемой риски
![2015-11-25 10 36 02](https://cloud.githubusercontent.com/assets/436951/11411724/310e2366-93e4-11e5-9f49-8ce9ccd0d8e4.png)

**Comment by DarkHobbit** [comment]
Нда, это, наверное, самое пакостное. Если ошибки округления, придётся опять алгоритм пересматривать...

**Comment by RandomAmbersky** [comment]
Предлагаю забить на поиск пакостного округления и использовать кошерное масштабирование как это реализовано в кошерной демке http://doc.qt.io/qt-5/qtwidgets-graphicsview-chip-example.html 
Попутно уйдет нерегулярность отрисовки рисок ( вот такая вот "зубатость" ) 
![2015-12-01 3 51 35](https://cloud.githubusercontent.com/assets/436951/11489274/04dc5372-97df-11e5-9d1e-0afcaf22acac.png)
которая вырождается в
![2015-12-01 3 51 49](https://cloud.githubusercontent.com/assets/436951/11489279/174389a4-97df-11e5-8bda-793c689b7525.png)

**Comment by DarkHobbit** [comment]
Кошерное масштабирование, как выяснилось, тут не при чём. Тут вопрос не в программной реализации, а в том, как это должно выглядеть (с точки зрения человека, который не знает Qt, не знает программирование, но знает арифметику и умеет мерять расстояния). В примере с чипами шкала однородная, и масштабировать её проще. А вот временная шкала неоднородна, начиная от месяцев и к более крупным единицам (ибо в месяце может быть от 28 до 31 дня).
Первый вариант - у всех дней одинаковая ширина в пикселях, тогда месяцы и годы будут переменной ширины
Второй вариант - одинаковая ширина в пикселях должна быть у основной единицы времени, будь то день, месяц, квартал или год. А все дочерние метки подстраиваются под неё.
Если рассматривать дни, недели, а промежуток брать максимум в 2-3 месяца, то в программе разница между первым и вторым практически незаметна. Соответственно у меня и дата пересчитывалась в X по простой пропорции. А вот как ты поставил год - так разница и выплыла. 
Ну так вот, по сути вопроса - какой подход правильнее, первый или второй? Или всё равно, тогда я выберу тот, который проще в реализации. (Впрочем, какой проще, я ещё не определился.)

**Comment by DarkHobbit** [comment]
Кстати, объективность проблемы подтверждается тем, что в QDate есть методы addDays, addMonths, addYears. При этом есть метод daysTo... а вот метода monthsTo уже нет :)

**Comment by DarkHobbit** [comment]
Не перетряхивая радикально концепцию, удалось свести эффект 1 марта к минимуму (коммит 58d88eb..59b8c86). К сожалению, "зубатость второго рода", которая показана на 3-й картинке, можно побороть только переходом на первый подход (дни одинаковой ширины). При втором подходе всегда можно найти масштаб, при котором месяцы с 30 днями будут влезать в пресловутые 2 пиксела на день, а вот с 31 днём - уже нет, и в программе на них срабатывает защита. Хотя и тут есть лазейка...

**Comment by DarkHobbit** [comment]
Зубатость второго рода победил. Попробуй задать отображение за год, выставить флаг на 1 марта и скажи, достотачно ли такой точности. Если да - я буду бороться с другими глюками.

**Comment by RandomAmbersky** [comment]
Задал за год, автоматом включается отображение в кварталах.. Почему-то плавность установки флажка куда-то исчезает,  можно только на начало месяца поставить. При этом виден сдвиг относительно риски. Если принудительно после этого выставить "месяцы" то риска будет аккурат напротив 1 марта.. наверное :) 
Попутно выяснилось следующее... при некотором выбранном масштабе ( как на рисунке например) получается сдвиг дат, т.е. если я кликаю на флажок "1 марта" и ставлю его на большую риску, он показывает дату на день меньше... И прочие риски показывают дату на день меньше чем та, на которую ставится флажок при переносе...

![2016-01-10 0 15 11](https://cloud.githubusercontent.com/assets/436951/12218422/c6bf0d26-b72f-11e5-8211-dfcc15160169.png)

**Comment by DarkHobbit** [comment]
> Задал за год, автоматом включается отображение в кварталах..
А у меня месяцы включаются...
![Entire Year](http://zvyozdochkin.ru/img-host/github/chronoline/clshotyear.png)
И флаг на 1 марта нормально становится...

**Comment by RandomAmbersky** [comment]
Дырки и две риски на шкале...
( ну еще флажок стоит на 1 января а показывает на 30 ноября, но это насколько я понимаю, еще не исправлено )
![2016-01-11 3 36 15](https://cloud.githubusercontent.com/assets/436951/12225139/2092ec7e-b815-11e5-88f1-b39ce62209ce.png)

**Comment by DarkHobbit** [comment]
Прямо Григорий Лепс какой-то... "Ды-ы-ы-ырки! И две риски на шкале..."

**Comment by DarkHobbit** [comment]
Дырок больше быть не должно.

**Comment by DarkHobbit** [comment]
> если я кликаю на флажок "1 марта" и ставлю его на большую риску, он показывает дату на день меньше...
Это просто в демке есть принудительное округление до целого дня (MainWindow::anyFlagDateChanged, выделено комментарием "force round to day"), а в строке состояния выводилась (ошибочно) дата после перемещения, но округления. Исправил.

**Comment by RandomAmbersky** [comment]
Супер! Работает!

**Comment by RandomAmbersky** [comment]
А нельзя чтобы 1 марта показывало например вот так:
![2016-01-12 14 57 33](https://cloud.githubusercontent.com/assets/436951/12263007/f3c7e162-b93c-11e5-9e14-e3f45905dbe0.png)
а не вот так:
![2016-01-12 14 57 47](https://cloud.githubusercontent.com/assets/436951/12263010/ffeecb68-b93c-11e5-9c5a-964fb51c85a1.png)
?

**Comment by DarkHobbit** [comment]
Вообще-то, по идее, оно должно быть прямо под риской, ибо риска и соответствует именно 0:00 1 марта. И с единицами по месяцы включительно так и есть. Но при переходе к кварталам всё-таки вылезает погрешность в районе плюс-минус один пиксел.
Нельзя ли её вообще убрать? Честно говоря, не знаю, надо копать достаточно глубоко. Всё, что лежало более-мене на поверхности, я уже зачистил.

**Comment by RandomAmbersky** [comment]
>Вообще-то, по идее, оно должно быть прямо под риской, ибо риска и соответствует именно 0:00 1 марта.

Ну да, только у меня не получается перемещением флажка установить его точно по риске, ибо он почему-то рисуется утолщенным, видимо в два пикселя ;)

**Comment by RandomAmbersky** [comment]
Кстати, для pair наверное тоже округлять надо ? Флажок устанавливается точно на 1 января, но в строке состояния все еще 31 декабря

![2016-01-12 18 52 15](https://cloud.githubusercontent.com/assets/436951/12268452/f49f85a6-b95d-11e5-8136-d606521462f6.png)

**Comment by DarkHobbit** [comment]
> Кстати, для pair наверное тоже округлять надо ?
Угу, сделал... Это (и предыдущее) были глюки демки, не библиотеки...

> почему-то рисуется утолщенным, видимо в два пикселя ;)
Выделенный - утолщённым, невыделенный - обычным :)

**Comment by RandomAmbersky** [comment]
![2016-02-05 20 57 00](https://cloud.githubusercontent.com/assets/436951/12864957/6c14b55c-ccaf-11e5-809c-1a6c4aa9bb65.png)

**Comment by RandomAmbersky** [comment]
Все будет хорошо.
