### ISSUE TITLE
сбой автоподбора единиц времени

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#17]
Сбой автовыбора единиц времени. Когда ( при периоде 01/01/2015-31/12/2015 ) начальную дату меняем ( курсор установлен на годе,  нажимаем два раза клавишу вниз ) на 01/01/2013 то при обратном возвращении на 01/01/2015 масштаб обратно не изменяется и по-прежнему показываются годы. По-видимому стоит только раз попасть на масштаб "Годы" как обратно на "месяцы" не переводится 

https://vimeo.com/147053964

**Comment by DarkHobbit** [comment]
Повторилось. :( Хотя не для любого диапазона это работает, несколько раз я с годов на месяцы возвращался.

**Comment by DarkHobbit** [comment]
А чем видео работы захватывалось? На маке какая-то встроенная программа есть?

**Comment by RandomAmbersky** [comment]
Да, там QuickTime Player который с системой идет. Позволяет захватывать весь экран или его часть, после захвата можно обрезать с начала и с конца - в общем все что нужно для работы :-}
А вот GIF ( https://github.com/DarkHobbit/chronoline/issues/22 ) уже через онлайн-конвертер делал, чтобы видео не заливать опять на vimeo.

p.s. Хотел было через Linux Mint с большого монитора снять, но там дефолтного чего-то ничего и не оказалось :( Надо качать или даже качать и компилить... бр-р... VLC может захватывать экран но не может ( кажется ) часть его :/

**Comment by DarkHobbit** [comment]
Что, и ничего из [этого списка](http://community.linuxmint.com/tutorial/view/1229) в репозитарии Минта нет?
Багу, вроде, поправил, с годов происходит возвращение на кварталы, смотри.

**Comment by RandomAmbersky** [comment]
Ура, блокировки нет! Демку использовать все приятнее и приятнее :)

>Что, и ничего из этого списка в репозитарии Минта нет?
Ну я бы предпочел чтобы сразу ставилось при установке системы, например Офис ставится... Так-то чего-то там в репозиториях есть, но надо это еще найти и выбрать...
