### ISSUE TITLE
Создать сигнал по изменению отображаемого интервала для класса ChronoLine

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#18]
.. для отслеживания минимального и максимального отображаемого размера.

**Comment by DarkHobbit** [comment]
Первая попытка реализации этого сигнала привела к интересному результату: сигнал посылается, данные в демку приходят, но... драг-н-дроп вместо перемещения области стал её расширять/ужимать. Видимо, происходит рекурсия, когда демка, получив сигнал, пытается сразу сделать перерисовку. Коммитить пока не стал, думаю, где это более корректно блокировать...

**Comment by RandomAmbersky** [comment]
Затейливо :) Блокировать в приложении скорее всего. Может (в приложении) флаг какой-нть включать когда изменения контролов идет от изменения масштаба в плагине, а не от пользователя, тогда в процедуре где вызывается изменение масштаба плагина при включенном флаге изменение масштаба не вызывать, во как %)

**Comment by DarkHobbit** [comment]
У меня и так уже есть (в библиотеке) lockAutoUpdate, для аналогичных случаев. Ну да, можно в начале обработчика сделать disconnect на события изменения значений редакторов дат, а в конце вернуть connect на место, и скорее всего, это всё решит. Но тяжеловато что-то для прикладного уровня. Ещё поковыряюсь, если по-другому не получится, сделаю так...

**Comment by RandomAmbersky** [comment]
слот-сигнал вообще штука мутная, программа через некоторое время начинает жить своей особой жизнью...  :)

**Comment by DarkHobbit** [comment]
По поводу особой жизни - вспомнилась классика...
http://lib.ru/RAZNOE/subway.txt

**Comment by DarkHobbit** [comment]
Сделал. Добавил ещё флаг в вызывающей программе.

**Comment by DarkHobbit** [comment]
Поторопился закоммитить... после введения флага перетаскивание работает нормально, зато максимальная дата перестала меняться вручную.

**Comment by DarkHobbit** [comment]
Поправил

**Comment by RandomAmbersky** [comment]
Эмм, теперь меняю даты в контролах вручную вводя туда значения и ничего не происходит - это так и задумано?
