### ISSUE TITLE
несколько январей за год... пирдуха в демке ;) 

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#19]
![2016-01-07 21 57 28](https://cloud.githubusercontent.com/assets/436951/12179764/c2b3ebf4-b589-11e5-99d3-b20843add5c4.png)

**Comment by DarkHobbit** [comment]
Это, похоже, старая ошибка вылезла... #15 лучше туда писать... Буду смотреть.
