### ISSUE TITLE
сбой плавности передвижения шкалы мышкой после изменения масштаба

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#20]
Запускаем демку, десять раз подряд нажимаем Ctrl - и шкала при зацеплении ее мышкой начинается двигаться отвратительно ( а если нажать девять и менее раз - прекрасная плавность! )

**Comment by DarkHobbit** [comment]
В строке состояния выводится реальная текущая единица. Если нажимая на Ctrl+-. смотреть на неё, то видно, что на 10-м нажатии происходит переход на недели, а на 22-м (#21) - на месяцы. При переходе от 10 к 19 нажатиям плавность постепенно возрастает, кстати.
Т.е., когда реальная единица занимает мало пикселов, плавность есть, когда много - нет. Т.е. там есть дискретность перемещения, косвенно связанная с текущей единицей. Вроде бы сам я такой эффект не вводил, буду разбираться, откуда он взялся.

**Comment by DarkHobbit** [comment]
Ага, недели победил (пока не коммитил), буду с месяцами бороться, всё же это стороны одной медали.
Суть бага была связана с тем, что addDays принимает на входе целое число, и для плавности его надо комбинировать с более прецизионными функциями. Чтобы побороть недели оказалось проще просто вместо addDays применить addSecs с соответствующим множителем. С месяцами придётся таки комбинировать из-за их неоднородности...

**Comment by DarkHobbit** [comment]
Победил и месяцы, закоммитил. Правда, конкретно на 22-й итерации первый сдвиг мышью получается впустую, второй уже работает нормально.

**Comment by RandomAmbersky** [comment]
И это ушло...
