### ISSUE TITLE
изменение размеров рисок шкалы при передвижении её мышкой

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#22]
![garmon convert-video-online com](https://cloud.githubusercontent.com/assets/436951/12231468/c22dd79e-b868-11e5-9b5a-178971eb7ab2.gif)

**Comment by DarkHobbit** [comment]
Я не очень понял, что там с размером происходит, но предлагаю потестить последнюю версию с постоянной шириной дней - там, по идее, много чего равномернее должно быть.

**Comment by RandomAmbersky** [comment]
Там с размером происходит следующее: в дате начала и дате окончания присутствуют часы и минуты ( без них все гладко двигается, без изменения масштаба рисок)
и вот когда пытаешься сдвинуть шкалу, то вместо движения получаем "сжатие" масштаба в результате чего начинает отображаться еще один день на шкале. 

https://vimeo.com/151481024

**Comment by DarkHobbit** [comment]
> в результате чего начинает отображаться еще один день на шкале. 
Да нет же, там один день с одно

**Comment by RandomAmbersky** [comment]
>Да нет же, там один день с одной стороны появляется, с другой исчезает. По-моему, нормальный сдвиг. 

Согласен, плохое видео записал.. Тут лучше видно что лишний день появляется..

https://vimeo.com/151501374

**Comment by DarkHobbit** [comment]
Да, повторяется. Похоже, это эффект, специфичный для недель и проявляется при достаточно малом сдвиге. Если единица - день, то всё двигается плавно и без "гармони", а если месяц и выше, то там шкала на очень малые сдвиги просто не реагирует, на больших - уже просто сдвигается, и без "гармони"...

**Comment by RandomAmbersky** [comment]
Да, про отсутствие реакции на малые сдвиги тоже хотел написать ;)

**Comment by DarkHobbit** [comment]
Это, похоже, продолжение той же проблемы на более крупных единицах :(

**Comment by DarkHobbit** [comment]
Гармонь на неделях вроде бы поборол. Осталось отсутствие сдвига на месяцах при недостаточно резком перетаскивании (гармони там и не было...).

**Comment by DarkHobbit** [comment]
Всё, там теперь тоже плавно скользит.

**Comment by RandomAmbersky** [comment]
Ура!!
