### ISSUE TITLE
смена отображения дни-часы при движении шкалы

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#23]
(возможно это часть бага https://github.com/DarkHobbit/chronoline/issues/22 и при исправлении уйдут оба )

https://vimeo.com/151500257

**Comment by DarkHobbit** [comment]
Чуть пошаманил с константами, попробуй ещё...

**Comment by RandomAmbersky** [comment]
Гм, теперь при непрерывном нажатии Ctrl- до часов отображение вообще не доходит...
В принципе в реальной программе планируется использовать только дни, и фиг бы с ним, но если уж сделано.. ну или тогда надо "часы" в выпадающем списке закомментарить ;)

**Comment by DarkHobbit** [comment]
Надо подумать

**Comment by DarkHobbit** [comment]
Сделал менее радикальный вариант.
До часов доходит, но они отображаются без минут, соответственно, не наползают друг на друга... ну и вроде бы нет скачков с дней на часы и назад.

**Comment by RandomAmbersky** [comment]
Вроде бы да, ушло...
