### ISSUE TITLE
О логике работы выбора флажков, находящихся на одной риске

### ISSUE THREAD

**Issue by RandomAmbersky** [DarkHobbit/chronoline#26]
Если несколько флажков стоят на одной риске ( в том числе это может быть и флажок от pairs ) то реализован очень удобный их перебор кликом мышки, но независимо от выбранного флажка мышкой двигается только один из них ( самый первый? )

Видимо это надо что-то в демке подправить, не в самом плагине?

**Comment by DarkHobbit** [comment]
В плагине. Но пока не очень понимаю, что именно. Надо подумать.
